//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCaptionTranslator.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveCaptionTranslator.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If set, continue executing the remaining activities even if the current activity has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContinueOnError に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IBM Watson Speech to Text Service APIKey に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeechToTextStreamingScope_APIKey_Description {
            get {
                return ResourceManager.GetString("SpeechToTextStreamingScope_APIKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIKey に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeechToTextStreamingScope_APIKey_DisplayName {
            get {
                return ResourceManager.GetString("SpeechToTextStreamingScope_APIKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IBM Watson Speech to Text AudioModel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeechToTextStreamingScope_AudioModel_Description {
            get {
                return ResourceManager.GetString("SpeechToTextStreamingScope_AudioModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AudioModel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeechToTextStreamingScope_AudioModel_DisplayName {
            get {
                return ResourceManager.GetString("SpeechToTextStreamingScope_AudioModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeechToTextStreamingScope_Description {
            get {
                return ResourceManager.GetString("SpeechToTextStreamingScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speech  To Text Streaming Scope に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeechToTextStreamingScope_DisplayName {
            get {
                return ResourceManager.GetString("SpeechToTextStreamingScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IBM Watson Speech to Text Service URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeechToTextStreamingScope_URL_Description {
            get {
                return ResourceManager.GetString("SpeechToTextStreamingScope_URL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeechToTextStreamingScope_URL_DisplayName {
            get {
                return ResourceManager.GetString("SpeechToTextStreamingScope_URL_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_Description {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Streaming Recognize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_DisplayName {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the text file path to output the voice recognition result text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_ExportFilePath_Description {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_ExportFilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_ExportFilePath_DisplayName {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_ExportFilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_LiveCaption_Description {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_LiveCaption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Live Caption に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_LiveCaption_DisplayName {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_LiveCaption_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If checked, Translate voice recognition result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_LiveTranslator_Description {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_LiveTranslator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LiveTranslator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_LiveTranslator_DisplayName {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_LiveTranslator_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_TranslatorAPIKey_Description {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_TranslatorAPIKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IBM Watson Language Translator Service APIKey に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_TranslatorAPIKey_DisplayName {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_TranslatorAPIKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IBM Watson Language Translator Service Model Id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_TranslatorModelId_Description {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_TranslatorModelId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translator Model Id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_TranslatorModelId_DisplayName {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_TranslatorModelId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IBM Watson Language Translator Service Translator URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_TranslatorURL_Description {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_TranslatorURL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translator URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartStreamingRecognize_TranslatorURL_DisplayName {
            get {
                return ResourceManager.GetString("StartStreamingRecognize_TranslatorURL_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StopStreamingRecognize_Description {
            get {
                return ResourceManager.GetString("StopStreamingRecognize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Streaming Recognize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StopStreamingRecognize_DisplayName {
            get {
                return ResourceManager.GetString("StopStreamingRecognize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout (milliseconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The activity timed out and was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Translator_Category {
            get {
                return ResourceManager.GetString("Translator_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value either for {0} or {1}, but not both. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide values for both {0} and {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot be used outside of a {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If LiveTranslator checked, Please provide a value for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationValue_LiveTranslator_Error {
            get {
                return ResourceManager.GetString("ValidationValue_LiveTranslator_Error", resourceCulture);
            }
        }
    }
}
