using System.ComponentModel;

namespace LiveCaptionTranslator.Enums
{
    public enum AudioModel
    {
        [Description("")]
        none,
        [Description("ar-AR_BroadbandModel")]
        ar_AR_BroadbandModel,
        [Description("de-DE_BroadbandModel")]
        de_DE_BroadbandModel,
        [Description("de-DE_NarrowbandModel")]
        de_DE_NarrowbandModel,
        [Description("en-GB_BroadbandModel")]
        en_GB_BroadbandModel,
        [Description("en-GB_NarrowbandModel")]
        en_GB_NarrowbandModel,
        [Description("en-US_BroadbandModel")]
        en_US_BroadbandModel,
        [Description("en-US_NarrowbandModel")]
        en_US_NarrowbandModel,
        [Description("en-US_ShortForm_NarrowbandModel")]
        en_US_ShortForm_NarrowbandModel,
        [Description("es-AR_BroadbandModel")]
        es_AR_BroadbandModel,
        [Description("es-AR_NarrowbandModel")]
        es_AR_NarrowbandModel,
        [Description("es-CL_BroadbandModel")]
        es_CL_BroadbandModel,
        [Description("es-CL_NarrowbandModel")]
        es_CL_NarrowbandModel,
        [Description("es-CO_BroadbandModel")]
        es_CO_BroadbandModel,
        [Description("es-CO_NarrowbandModel")]
        es_CO_NarrowbandModel,
        [Description("es-ES_BroadbandModel")]
        es_ES_BroadbandModel,
        [Description("es-ES_NarrowbandModel")]
        es_ES_NarrowbandModel,
        [Description("es-MX_BroadbandModel")]
        es_MX_BroadbandModel,
        [Description("es-MX_NarrowbandModel")]
        es_MX_NarrowbandModel,
        [Description("es-PE_BroadbandModel")]
        es_PE_BroadbandModel,
        [Description("es-PE_NarrowbandModel")]
        es_PE_NarrowbandModel,
        [Description("fr-FR_BroadbandModel")]
        fr_FR_BroadbandModel,
        [Description("fr-FR_NarrowbandModel")]
        fr_FR_NarrowbandModel,
        [Description("it-IT_BroadbandModel")]
        it_IT_BroadbandModel,
        [Description("it-IT_NarrowbandModel")]
        it_IT_NarrowbandModel,
        [Description("ja-JP_BroadbandModel")]
        ja_JP_BroadbandModel,
        [Description("ja-JP_NarrowbandModel")]
        ja_JP_NarrowbandModel,
        [Description("ko-KR_BroadbandModel")]
        ko_KR_BroadbandModel,
        [Description("ko-KR_NarrowbandModel")]
        ko_KR_NarrowbandModel,
        [Description("nl-NL_BroadbandModel")]
        nl_NL_BroadbandModel,
        [Description("nl-NL_NarrowbandModel")]
        nl_NL_NarrowbandModel,
        [Description("pt-BR_BroadbandModel")]
        pt_BR_BroadbandModel,
        [Description("pt-BR_NarrowbandModel")]
        pt_BR_NarrowbandModel,
        [Description("zh-CN_BroadbandModel")]
        zh_CN_BroadbandModel,
        [Description("zh-CN_NarrowbandModel")]
        zh_CN_NarrowbandModel
    }
}
